### PR TITLE
GAA-20 anchor tag fix for screen readers

### PR DESCRIPTION
**Pull request by dahfool**
To do (delete all that do not apply):

 - [x] Changelog entry added.

### CODE REVIEW

**Review by bobmeredith — APPROVED** [review]
Looks good

**Comment by webbyfox** [comment]
No version bump ?

**Comment by dahfool** [comment]
> Looks good

https://github.com/uktrade/directory-components/pull/345/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR3

**Comment by webbyfox** [comment]
Needs to do in `setup.py`

**Review by webbyfox — APPROVED** [review]
LGTM

**Review by depsiatwal — APPROVED** [review]

**Pull request merged**
